### ISSUE TITLE
Maybe common `.md` or `.rst` Doc works better in the repository?

### ISSUE THREAD

**Issue by EillesWan** [phoenixr-codes/mcstructure#3]
The aim to Documents are making it easy to explain how things works, however what you contains in this repository is a stuff of files what you want to put on the [site](https://phoenixr-codes.github.io/mcstructure/).

This cannot be easily read by a man while doing programming through his IDEs, so may it could be better if maybe some `.md` or `.rst` typed Documents can be put in the docs directory to replace the `.html`s and so on.

It is clear that a Docs Website is a great idea, but putting the stuff in another repository and open the GitHub Pages works well too.

If you may need a Chinese document translator, a helper is shining out in front of your eyes -- ME! Also that I can write some API documents in English too.

应该换一个好看一点的文档表达法，，，，现在的文档不是很全面，也不是很好读，如果换成md或者rst这种便于读的文档可能会好很多，如果要挂网站的化我建议另开新repo，这样也是不错的。

**Comment by phoenixr-codes** [comment]
The `documentation-update` branch is going to be written in Markdown and contain tutorials.

The docstrings will stay in sphinx rst so users who do not use IDEs such as Visual Studio Code are able to refer to the documentation page which provides links to other python objects etc for a comfortable user experience.

The documentation will then be hosted on readthedocs instead of GitHub Pages to keep the file structure simple.
